site_name: AI Data Platform Study
site_description: AI Data Platform & Local LLM Study
theme:
  name: material
  language: ko

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md

  - Roadmap:
      - 학습 로드맵: roadmap/study-roadmap.md

  - Setting:
      - MkDocs 문서 사이트 구축 가이드: setting/mkdocs_github_pages_guide.md
      - MkDocs 문서 사이트 구축 가이드(windows): setting/mkdocs_github_pages_guide_windows.md
      - MkDocs 문서 Deploy 가이드: setting/mkdocs_github_pages_guide_deploy.md
      - Mac Mini 기반 AI LAB 구축 가이드: setting/macmini_ai_lab_guide.md



  - Study:
      - Step1 local LLM : 
        - Local LLM 구축 가이드: study/step1/step1_local_llm_setup_guide.md
        - LLM 모델 크기 이해: study/step1/local_llm_model_size_guide.md
        - LLM 모델 크기 완전 이해 가이드: study/step1/local_llm_model_size_guide_detail.md
        - Python 가상환경과 Ollama 연동 가이드: study/step1/Step1-3_Python_Virtual_Environment_and_Ollama_Guide.md
        - Open WebUI 구축 및 Docker 이해 가이드: study/step1/Step1-4_Open_WebUI_Docker_Guide.md
        - Prompt 실습 가이드: study/step1/Step1-5_Prompt_Practice_Guide.md
      - Step2 RAG: study/data-lakehouse.md
      - Step3 Agent: study/iceberg.md
      - Step4 AI Data Platform: study/delta-lake.md
      - Step5 AI Serving Platform: study/delta-lake.md

